#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  8 20:18:59 2022

@author: songz
"""

import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument('-a', '--alignment', \
                    type=argparse.FileType('r'), \
                    nargs='+', \
                    default=sys.stdin, \
                    help='Specify the alignment pair as FILE_1 FILE_2.')
parser.add_argument('-o', '--output', help='Output alignment.')
args = parser.parse_args()
aln_files   = args.alignment
out_file    = args.output

if len(aln_files) != 2:
    print('Found {0} files, requires 2 files.'.format(len(aln_files)))
else:
    r1 = {}
    for line in aln_files[0]:
        line = line.strip('\n').split('\t')
        query = line[0].split('/')[0]
        target = line[1]
        pident = float(line[2])
        r1[(query,target)] = [pident]
    print('Found {0} alignments in r1'.format(len(r1)))
    r2 = {}
    for line in aln_files[1]:
        line = line.strip('\n').split('\t')
        query = line[0].split('/')[0]
        target = line[1]
        pident = float(line[2])
        r2[(query,target)] = pident
    print('Found {0} alignments in r2'.format(len(r2)))

# Update r1 with items in r2
for key, value in r2.items():
    try:
        r1[key].append(value)
    except KeyError:
        pass

# Write to disk
count = 0
with open(out_file, 'w') as f:
    for key, value in r1.items():
        if len(value) == 2:
            count += 1
            f.write('{0}\t{1}\t{2}\n'.format(key[0], key[1], (value[0]+value[1])/2))
        else:
            pass
print('Found {0} alignments in both.'.format(count))
